name: 'Integration Test'
description: 'Test production build locally'
inputs:
  base-path: 
    description: 'base path used for test'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: npm install serve # npx does not run properly on Windows; install serve to use later
      shell: bash
    - name: Download production build
      uses: actions/download-artifact@v4
      with:
        name: build
        path: build/${{ inputs.base-path }}
    - name: integration test
      uses: cypress-io/github-action@v6
      with:
        start: npx --yes serve ./build --listen 3000
        config: baseUrl=http://localhost:3000/${{ inputs.base-path }}
        browser: chrome
    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        if: failure()
        retention-days: 7