/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    java
    antlr
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    antlr("org.antlr:antlr4:4.13.2")
    implementation("org.antlr:antlr4:4.13.2")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

task("generateJsTarget", JavaExec::class) {

  classpath = sourceSets["main"].runtimeClasspath

  mainClass = "org.antlr.v4.Tool"

  // arguments to pass to the application
  args  = listOf(
    "-Dlanguage=JavaScript", 
    "-o", "./build/js/",
    "-Xexact-output-dir", 
    "./src/main/antlr/FoodDescription.g4", 
    "./src/main/antlr/Amount.g4"
  )
}
