# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build app
      uses: ./.github/actions/build
    - name: Upload production build
      uses: actions/upload-artifact@v4
      with:
        name: build
        if-no-files-found: error
        path: build
        retention-days: 1

  integration-test:
    needs: [ build ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        browser: [ chrome ]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: npm install serve # npx does not run properly on Windows; install serve to use later
    - name: Download production build
      uses: actions/download-artifact@v4
      with:
        name: build
        path: build
    - name: integration test
      uses: cypress-io/github-action@v6
      with:
        start: npx --yes serve ./build --listen 3000
        browser: ${{ matrix.browser }}
