# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, cd ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Generate parser source code
      run: npm run gen-parser
    - run: npm ci
    - run: npm test
    - name: Builds the app for production
      if: ${{ github.ref == 'refs/heads/cd' }}
      run: npm run build
    - name: 'Upload Artifact'
      if: ${{ github.ref == 'refs/heads/cd' }}
      uses: actions/upload-artifact@v2
      with:
        name: diet-diary_build
        path: build
        retention-days: 1

  deploy:
    if: ${{ github.ref == 'refs/heads/cd' }}
    runs-on: ubuntu-latest
    steps:

