name: Draft Release
on:
  push:
    branches: [ main, draft-release ]
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: new tag version
        id: new_tag
        run: |
          # Set the new tag
          echo "tag=2.43.0" >> $GITHUB_ENV

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          tag="${{ steps.new_tag.outputs.tag }}"
          # Get the latest tag
          latest_tag="$(git describe --tags --abbrev=0)"
          # Get the last commit message
          last_commit_message=$(git log -1 --pretty=%B)
          # Create a draft release
          gh release create "v$tag" --title "v$tag $last_commit_message" --generate-notes --notes-start-tag "$latest_tag" --draft