# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build

    # deploy to github.io by copying the build files
    - name: Pushes to ZengLawrence.github.io repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.CODE_COMMIT_PERSONAL_TOKEN }}
      with:
        source-directory: 'build'
        destination-github-username: 'ZengLawrence'
        destination-repository-name: 'ZengLawrence.github.io'
        user-email: lawrence.zeng@gmail.com
        target-branch: main
